### ISSUE TITLE
进度条的问题（没有达到100%）

### ISSUE THREAD

**Issue by s1h3ibai** [ForestsKing/GLAFF#11]
100%|██████████| 321/321 [00:01<00:00, 205.96it/s]
100%|██████████| 103/103 [00:00<00:00, 525.53it/s]
  0%|          | 0/321 [00:00<?, ?it/s]Epoch: 2 || Train Loss: 0.368212 Valid Loss: 0.371207 || Cost: 1.755513s
Validation loss decreased (0.37675396 --> 0.37120744).  Saving model ...

100%|██████████| 321/321 [00:01<00:00, 190.76it/s]
100%|██████████| 103/103 [00:00<00:00, 203.08it/s]
  0%|          | 0/321 [00:00<?, ?it/s]Epoch: 3 || Train Loss: 0.364127 Valid Loss: 0.367679 || Cost: 2.189925s
Validation loss decreased (0.37120744 --> 0.36767923).  Saving model ...  实验中 最下面的进度条没有达到100%请问是什么原因？会不会影响最终的结果？

**Comment by ForestsKing** [comment]
I am unable to reproduce this error. It might just be a minor visual issue and should not affect the final result.

```
>>>>>>>>  initing : DLinear_Plugin_ETTh1_96_192_0  <<<<<<<<

Use GPU: cuda:0
Train Data Shape:  (10452, 7)
Valid Data Shape:  (3484, 7)
Test Data Shape:  (3484, 7)

>>>>>>>>  training : DLinear_Plugin_ETTh1_96_192_0  <<<<<<<<

100%|█████████████████████████████████████████| 318/318 [00:04<00:00, 70.98it/s]
100%|████████████████████████████████████████| 100/100 [00:00<00:00, 235.86it/s]
Epoch: 0 || Train Loss: 0.519117 Valid Loss: 0.474987 || Cost: 4.905234s
Validation loss decreased (inf --> 0.47498748).  Saving model ...

100%|█████████████████████████████████████████| 318/318 [00:04<00:00, 77.34it/s]
100%|████████████████████████████████████████| 100/100 [00:00<00:00, 231.75it/s]
Epoch: 1 || Train Loss: 0.447693 Valid Loss: 0.474028 || Cost: 4.543689s
Validation loss decreased (0.47498748 --> 0.47402848).  Saving model ...

```
