### ISSUE TITLE
the meaning of the  Robust Denormalizer 

### ISSUE THREAD

**Issue by linbingkong** [ForestsKing/GLAFF#12]
x_enc_map = (x_enc_map - robust_means_map) / robust_stdev_map * robust_stdev_true + robust_means_true

        x_dec_map = (x_dec_map - robust_means_map) / robust_stdev_map * robust_stdev_true + robust_means_true
        
robust_means_map means the median of the initial mapping  ̃X (history time data),robust_stdev_map means the quantile of history time data,However, robust_stdev_true and robust_means_true represent the median and quantile of historical values.Why can time-related data and feature data be mixed together for calculation? What is the significance of doing this?In the above text, mapping the time-related data and converting its dimension into the same dimension as the feature is also for the purpose of coupling here?

**Comment by ForestsKing** [comment]
We have already transformed the time-related data from the timestamp space to the feature space using the mapper. Similar to TIME WEAVER [1], the corresponding observational data is generated based on the timestamps, enabling mixed computations.

[1] TIME WEAVER: A Conditional Time Series Generation Model, ICML 2024
