### ISSUE TITLE
I didn't get a better result

### ISSUE THREAD

**Issue by zhhugh** [ForestsKing/GLAFF#2]
Hello, in your paper, I found you get great scores on many datasets, but I can't reproduce your results. The original model get a better result than your plugin model. 

iTransformer_Plugin_electricity_96_96_0  
Train:32.9569 s, Test:5.3187 s, Size:73.9528 MB
MSE:0.1542, MAE:0.2475

iTransformer_Standard_electricity_96_96_0  
Train:25.5487 s, Test:4.6230 s, Size:48.4828 MB
MSE:0.1526, MAE:0.2462

**Comment by nnstake** [comment]
There is a significant difference between the baseline in the paper and the results of a normal paper

**Comment by ForestsKing** [comment]
Correcting the timestamps in the electricity dataset could be beneficial. To my knowledge, most dataset currently utilized in the field originate from Autoformer. The timestamps in the preprocessed [CSV file](https://drive.google.com/drive/folders/1ZhaQwLYcnhT5zEEZhBTo03-jDwl7bt7v) (2016-2019)available on their Google Cloud Drive do not align with the time span recorded in their [paper](https://arxiv.org/pdf/2106.13008) (2012-2014) (and the original [TXT file](https://archive.ics.uci.edu/dataset/321/electricityloaddiagrams20112014) (2011-2014)).
