### ISSUE TITLE
Doubts about the experimental results

### ISSUE THREAD

**Issue by nnstake** [ForestsKing/GLAFF#3]
Why are the results presented in the paper significantly different from those of other papers. Take the simplest ETTh1 as an example. Generally, the results of a paper are between 0.36-0.54. Why is the iTransformer in your paper always between 0.42-0.72?

**Comment by ForestsKing** [comment]
Rather than solely comparing absolute prediction error magnitudes, a thorough examination of the experimental setup—such as dataset segmentation, sliding window strategy, and normalization methods—should address your questions.
