### ISSUE TITLE
Data preprocessing bug.

### ISSUE THREAD

**Issue by zezhishao** [ForestsKing/GLAFF#5]
Hi, dear author,

Thank you for contributing such valuable work to the community!

I wanted to bring a data processing issue to your attention. Typically, data normalization should be based solely on the training data to ensure that the validation and test data remain unseen during this step. You can see the relevant code here: https://github.com/ForestsKing/GLAFF/blob/c91679403b879c892f21c22eb0f53f314711d6f0/data/dataset.py#L10-L30.

This bug likely doesn’t affect GLAFF's validity but could have a notable impact on error metrics (for both baselines and GLAFF) on certain datasets, such as Traffic, potentially making comparisons with other papers unreliable.

**Comment by ForestsKing** [comment]
Thank you for your attention and acknowledgment of our work. We have resolved the data processing issues and will release an updated version with the corrected experimental results shortly. Thank you once again for your reminder.
