### ISSUE TITLE
Poor results when running test.sh with provided dataset and checkpoint

### ISSUE THREAD

**Issue by SkyKingL** [ForestsKing/GLAFF#8]
Your work is excellent. However, when I downloaded the dataset and checkpoint from the links provided in your repository and executed `bash ./test.sh`, I got the results shown in the two images below. Obviously, these results are poor in quality. Could you help identify if I missed any steps? By the way, I'm using Python 3.12.7 and PyTorch 2.5.1+cu118, which are different from the versions specified in your repository, but I don't think this is the cause of the poor results.

![image](https://github.com/user-attachments/assets/c531aed0-a12c-469d-bd22-376b3679d7c2)
![image](https://github.com/user-attachments/assets/d40d5a58-d025-4cf8-8ec6-85af7cf0a80d)

**Comment by ForestsKing** [comment]
Thank you for your attention to our work. We previously made some changes to the code but didn’t have time to update the checkpoints. Our latest version should address your concerns. We apologize for any inconvenience caused.
