### ISSUE TITLE
Still Poor

### ISSUE THREAD

**Issue by SkyKingL** [ForestsKing/GLAFF#9]
Your work is excellent. However, when I downloaded the dataset and checkpoint from the links provided in your repository and executed bash ./test.sh, I got the results shown in the two images below. Obviously, these results are poor in quality. Could you help identify if I missed any steps? By the way, I'm using Python 3.12.7 and PyTorch 2.5.1+cu118, which are different from the versions specified in your repository, but I don't think this is the cause of the poor results.

![image](https://github.com/user-attachments/assets/244b673f-6892-4f8c-b7c5-0dfea280ce38)
![image](https://github.com/user-attachments/assets/3b0e9468-b2fd-4bce-8475-e669e6a27043)

![image](https://github.com/user-attachments/assets/66492150-b579-4864-8579-f5e5cdd983f3)

**Comment by ForestsKing** [comment]
This discrepancy primarily stems from the unreasonable normalization method used in the experiments of our paper, as detailed in #5. Fortunately, after fixing this bug, GLAFF can still function normally.
